"""add booking reference to reservations

Revision ID: 380fdeb791f6
Revises: a883ce1362a2
Create Date: 2026-10-01 15:20:39.086638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '380fdeb791f6'
down_revision: Union[str, Sequence[str], None] = 'a883ce1362a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    op.add_column(
        'reservations',
        sa.Column('booking_reference', sa.String(), nullable=True)
    )

    # Generate a temporary unique reference for existing reservations
    connection = op.get_bind()

    reservations = connection.execute(
        sa.text("SELECT id FROM reservations")
    ).fetchall()

    for reservation in reservations:
        reference = f"EVT-{reservation.id:06d}"

        connection.execute(
            sa.text(
                """
                UPDATE reservations
                SET booking_reference = :reference
                WHERE id = :reservation_id
                """
            ),
            {
                "reference": reference,
                "reservation_id": reservation.id
            }
        )

    op.create_index(
        op.f('ix_reservations_booking_reference'),
        'reservations',
        ['booking_reference'],
        unique=True
    )

    # Existing reservations now have references,
    # so the column can safely become required.
    op.alter_column(
        'reservations',
        'booking_reference',
        existing_type=sa.String(),
        nullable=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reservations_booking_reference'), table_name='reservations')
    op.drop_column('reservations', 'booking_reference')
    # ### end Alembic commands ###
